name: Deploy

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed
    # pull_request:
    #     types: [closed]
        # branches: main

jobs:
    deploy-web:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest
        steps:
            # - name: Checkout repository
            #   uses: actions/checkout@v2
            # - run: echo "This job was tirggered by a pull request event"
            # - run: echo "Your sercret is ${{ secrets.MY_FIRST_KEY }}"
            - name: deploy to ec2
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.EC2_HOST }}
                username:  ${{secrets.EC2_USERNAME }}
                key: ${{ secrets.MY_FIRST_KEY }}
                port: ${{ secrets.EC2_PORT }}
                script: |
                    echo "Your port is ${{ secrets.EC2_PORT }}"
                    docker pull travis027/cicd-test:latest
                    docker stop $(docker ps -q --filter ancestor=travis027/cicd-test)
                    docker rm $(docker ps -a -q --filter ancestor=travis027/cicd-test)
                    docker run -d -p 80:3000 travis027/cicd-test:latest
                    # cd /home/ubuntu/cicd-pipeline-workshop
                    # git pull
                    # pm2 restart src/server.js